name: Deploy Hakyll website to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1" # 8AM CET/11PM PT on Mondays
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: haskell-actions/setup@v2
        name: Setup Haskell Stack
        id: setup
        with:
          ghc-version: "9.6.6"
          enable-stack: true
          stack-version: "latest"
      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-stack-${{ steps.setup.outputs.stack-version }}
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ env.key }}-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: ${{ env.key }}-
      - name: Build dependencies
        run: stack build --system-ghc --only-dependencies
      - uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ steps.cache.outputs.cache-primary-key }}
      - name: Build site executable
        run: stack --system-ghc build
      - name: Build site
        run: stack --system-ghc exec site rebuild
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: "C07MHPCCXD1"
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
